apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stellar-horizon-redis
  labels:
    app: stellar-horizon-redis
    role: master
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stellar-horizon-redis
        role: master
        tier: backend
    spec:
      containers:
      - name: stellar-horizon-redis
        image: gcr.io/google_containers/redis:e2e
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
