apiVersion: v1
kind: Service
metadata:
  name: stellar-horizon
  labels:
    app: stellar-horizon
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    run: stellar-horizon
