apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-instance-credentials
type: Opaque
data:
  # base64 cloudsql-instance-credentials.json | pbcopy
  credentials.json: ##please set base64 encoded service account json formatted key string##
