apiVersion: v1
kind: PersistentVolume
metadata:
  name: stellar-core-pv
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: stellar-core-disk
    fsType: ext4
